# Generated by Django 4.1.1 on 2022-09-25 08:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('org_username', models.CharField(max_length=100, unique=True)),
                ('org_name', models.CharField(max_length=200)),
                ('org_description', models.TextField(blank=True, null=True)),
                ('org_logo', models.FileField(blank=True, null=True, upload_to='organizations/logo')),
                ('is_org_verified', models.BooleanField(default=False)),
                ('is_org_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organizations',
            },
        ),
    ]
